//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Reloaded Launcher")]
[assembly: System.Reflection.AssemblyDescription("Reloaded Mod Loader Launcher")]
[assembly: System.Reflection.AssemblyProduct("Reloaded Mod Loader")]
[assembly: System.Reflection.AssemblyCopyright("Sewer56lol, 2018")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyInformationalVersion("0.8.5.8396cf9")]
[assembly: System.Reflection.AssemblyVersion("0.8.5")]
[assembly: System.Reflection.AssemblyFileVersion("0.8.5")]


