//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyTitle("Reloaded Launcher")]
[assembly: System.Reflection.AssemblyDescription("Reloaded Mod Loader Launcher")]
[assembly: System.Reflection.AssemblyProduct("Reloaded Mod Loader")]
[assembly: System.Reflection.AssemblyCopyright("Sewer56lol, 2018")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: AssemblyVersion("1.0.2")]
[assembly: AssemblyFileVersion("1.0.2")]
[assembly: AssemblyMetadata("SquirrelAwareVersion", "1")]
[assembly: CLSCompliant(false)]
